<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-android36.0</TargetFramework>
    <SupportedOSPlatformVersion>29</SupportedOSPlatformVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU;ARM64;ARM32</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PasswordManagerLocal.Backend\PasswordManagerLocal.Backend.csproj" />
    <ProjectReference Include="..\PasswordManagerLocal.Backend.Hosting\PasswordManagerLocal.Backend.Hosting.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PasswordManagerLocal.Contracts\PasswordManagerLocal.Contracts.csproj" />
  </ItemGroup>

</Project>
