using PasswordManagerLocal.Windows.EndpointRpc.Contracts;
using PasswordManagerLocal.Windows.EndpointRpc.Contracts.Requests;
using PasswordManagerLocal.Windows.EndpointRpc.Contracts.Responses;

namespace PasswordManagerLocal.Windows.EndpointRpc.Metadata;

public static class EndpointOperationManifest
{
    private static readonly IReadOnlyList<EndpointOperationDescriptor> Descriptors =
    [
        new(EndpointOperationId.Register, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.RegisterAsync), typeof(RegisterEndpointRequest), typeof(RegisterEndpointResponse), EndpointOperationCancellationClassification.SideEffectingUnknownOutcome, true, false, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.Login, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.LoginAsync), typeof(LoginEndpointRequest), typeof(LoginEndpointResponse), EndpointOperationCancellationClassification.SideEffectingUnknownOutcome, true, false, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.RenewAuthSession, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.RenewAuthSessionAsync), typeof(RenewAuthSessionEndpointRequest), typeof(RenewAuthSessionEndpointResponse), EndpointOperationCancellationClassification.SideEffectingUnknownOutcome, true, false, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.Logout, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.LogoutAsync), typeof(LogoutEndpointRequest), typeof(LogoutEndpointResponse), EndpointOperationCancellationClassification.CriticalAdmittedOperation, true, true, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.GetAuthSessionStatus, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.GetAuthSessionStatusAsync), typeof(GetAuthSessionStatusEndpointRequest), typeof(GetAuthSessionStatusEndpointResponse), EndpointOperationCancellationClassification.ReadOnlySafelyCancellable, false, true, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.ChangeMasterPassword, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.ChangeMasterPasswordAsync), typeof(ChangeMasterPasswordEndpointRequest), typeof(ChangeMasterPasswordEndpointResponse), EndpointOperationCancellationClassification.CriticalAdmittedOperation, true, false, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.GetUserProfileInfo, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.GetUserProfileInfoAsync), typeof(GetUserProfileInfoEndpointRequest), typeof(GetUserProfileInfoEndpointResponse), EndpointOperationCancellationClassification.ReadOnlySafelyCancellable, false, true, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.DeleteUserAccount, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.DeleteUserAccountAsync), typeof(DeleteUserAccountEndpointRequest), typeof(DeleteUserAccountEndpointResponse), EndpointOperationCancellationClassification.CriticalAdmittedOperation, true, false, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.ChangeUsername, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.ChangeUsernameAsync), typeof(ChangeUsernameEndpointRequest), typeof(ChangeUsernameEndpointResponse), EndpointOperationCancellationClassification.CriticalAdmittedOperation, true, false, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.UpdateUserProfileInfo, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.UpdateUserProfileInfoAsync), typeof(UpdateUserProfileInfoEndpointRequest), typeof(UpdateUserProfileInfoEndpointResponse), EndpointOperationCancellationClassification.CriticalAdmittedOperation, true, false, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.GetLocalDeviceInfo, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.GetLocalDeviceInfoAsync), typeof(GetLocalDeviceInfoEndpointRequest), typeof(GetLocalDeviceInfoEndpointResponse), EndpointOperationCancellationClassification.ReadOnlySafelyCancellable, false, true, false, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.GetLocalUserSyncOn, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.GetLocalUserSyncOnAsync), typeof(GetLocalUserSyncOnEndpointRequest), typeof(GetLocalUserSyncOnEndpointResponse), EndpointOperationCancellationClassification.ReadOnlySafelyCancellable, false, true, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.SetLocalUserSyncOn, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.SetLocalUserSyncOnAsync), typeof(SetLocalUserSyncOnEndpointRequest), typeof(SetLocalUserSyncOnEndpointResponse), EndpointOperationCancellationClassification.IdempotentMutation, true, true, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.SetLocalDeviceName, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.SetLocalDeviceNameAsync), typeof(SetLocalDeviceNameEndpointRequest), typeof(SetLocalDeviceNameEndpointResponse), EndpointOperationCancellationClassification.IdempotentMutation, true, true, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.GetUserDevices, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.GetUserDevicesAsync), typeof(GetUserDevicesEndpointRequest), typeof(GetUserDevicesEndpointResponse), EndpointOperationCancellationClassification.ReadOnlySafelyCancellable, false, true, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumCollectionResponsePayloadSize),
        new(EndpointOperationId.SetUserDeviceName, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.SetUserDeviceNameAsync), typeof(SetUserDeviceNameEndpointRequest), typeof(SetUserDeviceNameEndpointResponse), EndpointOperationCancellationClassification.IdempotentMutation, true, true, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.SetUserDeviceSyncOn, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.SetUserDeviceSyncOnAsync), typeof(SetUserDeviceSyncOnEndpointRequest), typeof(SetUserDeviceSyncOnEndpointResponse), EndpointOperationCancellationClassification.IdempotentMutation, true, true, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.UnblockUserDevice, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.UnblockUserDeviceAsync), typeof(UnblockUserDeviceEndpointRequest), typeof(UnblockUserDeviceEndpointResponse), EndpointOperationCancellationClassification.IdempotentMutation, true, true, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.DisconnectUserDevice, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.DisconnectUserDeviceAsync), typeof(DisconnectUserDeviceEndpointRequest), typeof(DisconnectUserDeviceEndpointResponse), EndpointOperationCancellationClassification.CriticalAdmittedOperation, true, false, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.StartDeviceEnrollment, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.StartDeviceEnrollmentAsync), typeof(StartDeviceEnrollmentEndpointRequest), typeof(StartDeviceEnrollmentEndpointResponse), EndpointOperationCancellationClassification.SideEffectingUnknownOutcome, true, false, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.GetDeviceEnrollmentStatus, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.GetDeviceEnrollmentStatusAsync), typeof(GetDeviceEnrollmentStatusEndpointRequest), typeof(GetDeviceEnrollmentStatusEndpointResponse), EndpointOperationCancellationClassification.ReadOnlySafelyCancellable, false, true, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.CancelDeviceEnrollment, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.CancelDeviceEnrollmentAsync), typeof(CancelDeviceEnrollmentEndpointRequest), typeof(CancelDeviceEnrollmentEndpointResponse), EndpointOperationCancellationClassification.IdempotentMutation, true, true, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.AddDeviceByCode, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.AddDeviceByCodeAsync), typeof(AddDeviceByCodeEndpointRequest), typeof(AddDeviceByCodeEndpointResponse), EndpointOperationCancellationClassification.CriticalAdmittedOperation, true, false, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.RestoreRememberedSessions, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.RestoreRememberedSessionsAsync), typeof(RestoreRememberedSessionsEndpointRequest), typeof(RestoreRememberedSessionsEndpointResponse), EndpointOperationCancellationClassification.SideEffectingUnknownOutcome, true, false, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.InitializeRememberMeSession, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.InitializeRememberMeSessionAsync), typeof(InitializeRememberMeSessionEndpointRequest), typeof(InitializeRememberMeSessionEndpointResponse), EndpointOperationCancellationClassification.SideEffectingUnknownOutcome, true, false, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.SetRememberMe, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.SetRememberMeAsync), typeof(SetRememberMeEndpointRequest), typeof(SetRememberMeEndpointResponse), EndpointOperationCancellationClassification.IdempotentMutation, true, true, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.GetSavedPasswords, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.GetSavedPasswordsAsync), typeof(GetSavedPasswordsEndpointRequest), typeof(GetSavedPasswordsEndpointResponse), EndpointOperationCancellationClassification.ReadOnlySafelyCancellable, false, true, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumResponsePayloadSize, EndpointRpcLimits.MaximumLargeResultTotalBytes),
        new(EndpointOperationId.AddNewPassword, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.AddNewPasswordAsync), typeof(AddNewPasswordEndpointRequest), typeof(AddNewPasswordEndpointResponse), EndpointOperationCancellationClassification.CriticalAdmittedOperation, true, false, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.RemovePasswords, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.RemovePasswordsAsync), typeof(RemovePasswordsEndpointRequest), typeof(RemovePasswordsEndpointResponse), EndpointOperationCancellationClassification.CriticalAdmittedOperation, true, true, true, EndpointRpcLimits.MaximumBulkRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.GetUnsecurePassword, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.GetUnsecurePasswordAsync), typeof(GetUnsecurePasswordEndpointRequest), typeof(GetUnsecurePasswordEndpointResponse), EndpointOperationCancellationClassification.ReadOnlySafelyCancellable, false, true, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.UpdatePassword, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.UpdatePasswordAsync), typeof(UpdatePasswordEndpointRequest), typeof(UpdatePasswordEndpointResponse), EndpointOperationCancellationClassification.CriticalAdmittedOperation, true, true, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.ExportPasswordsToUser, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.ExportPasswordsToUserAsync), typeof(ExportPasswordsToUserEndpointRequest), typeof(ExportPasswordsToUserEndpointResponse), EndpointOperationCancellationClassification.CriticalAdmittedOperation, true, false, true, EndpointRpcLimits.MaximumBulkRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.AddCustomUserColors, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.AddCustomUserColorsAsync), typeof(AddCustomUserColorsEndpointRequest), typeof(AddCustomUserColorsEndpointResponse), EndpointOperationCancellationClassification.CriticalAdmittedOperation, true, false, true, EndpointRpcLimits.MaximumBulkRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.DeleteCustomUserColors, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.DeleteCustomUserColorsAsync), typeof(DeleteCustomUserColorsEndpointRequest), typeof(DeleteCustomUserColorsEndpointResponse), EndpointOperationCancellationClassification.CriticalAdmittedOperation, true, true, true, EndpointRpcLimits.MaximumBulkRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.ExportCustomUserColorsToUser, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.ExportCustomUserColorsToUserAsync), typeof(ExportCustomUserColorsToUserEndpointRequest), typeof(ExportCustomUserColorsToUserEndpointResponse), EndpointOperationCancellationClassification.CriticalAdmittedOperation, true, false, true, EndpointRpcLimits.MaximumBulkRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.UpdateCustomUserColor, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.UpdateCustomUserColorAsync), typeof(UpdateCustomUserColorEndpointRequest), typeof(UpdateCustomUserColorEndpointResponse), EndpointOperationCancellationClassification.CriticalAdmittedOperation, true, true, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.AddPasswordTag, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.AddPasswordTagAsync), typeof(AddPasswordTagEndpointRequest), typeof(AddPasswordTagEndpointResponse), EndpointOperationCancellationClassification.CriticalAdmittedOperation, true, false, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.DeletePasswordTag, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.DeletePasswordTagAsync), typeof(DeletePasswordTagEndpointRequest), typeof(DeletePasswordTagEndpointResponse), EndpointOperationCancellationClassification.CriticalAdmittedOperation, true, true, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.ExportPasswordTagsToUser, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.ExportPasswordTagsToUserAsync), typeof(ExportPasswordTagsToUserEndpointRequest), typeof(ExportPasswordTagsToUserEndpointResponse), EndpointOperationCancellationClassification.CriticalAdmittedOperation, true, false, true, EndpointRpcLimits.MaximumBulkRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
        new(EndpointOperationId.UpdatePasswordTag, nameof(PasswordManagerLocal.Backend.Abstractions.IEndpoints.UpdatePasswordTagAsync), typeof(UpdatePasswordTagEndpointRequest), typeof(UpdatePasswordTagEndpointResponse), EndpointOperationCancellationClassification.CriticalAdmittedOperation, true, true, true, EndpointRpcLimits.MaximumSmallRequestPayloadSize, EndpointRpcLimits.MaximumSmallResponsePayloadSize),
    ];

    public static IReadOnlyList<EndpointOperationDescriptor> All => Descriptors;

    public static EndpointOperationDescriptor Get(EndpointOperationId operationId) => operationId switch
    {
        EndpointOperationId.Register => Descriptors[0],
        EndpointOperationId.Login => Descriptors[1],
        EndpointOperationId.RenewAuthSession => Descriptors[2],
        EndpointOperationId.Logout => Descriptors[3],
        EndpointOperationId.GetAuthSessionStatus => Descriptors[4],
        EndpointOperationId.ChangeMasterPassword => Descriptors[5],
        EndpointOperationId.GetUserProfileInfo => Descriptors[6],
        EndpointOperationId.DeleteUserAccount => Descriptors[7],
        EndpointOperationId.ChangeUsername => Descriptors[8],
        EndpointOperationId.UpdateUserProfileInfo => Descriptors[9],
        EndpointOperationId.GetLocalDeviceInfo => Descriptors[10],
        EndpointOperationId.GetLocalUserSyncOn => Descriptors[11],
        EndpointOperationId.SetLocalUserSyncOn => Descriptors[12],
        EndpointOperationId.SetLocalDeviceName => Descriptors[13],
        EndpointOperationId.GetUserDevices => Descriptors[14],
        EndpointOperationId.SetUserDeviceName => Descriptors[15],
        EndpointOperationId.SetUserDeviceSyncOn => Descriptors[16],
        EndpointOperationId.UnblockUserDevice => Descriptors[17],
        EndpointOperationId.DisconnectUserDevice => Descriptors[18],
        EndpointOperationId.StartDeviceEnrollment => Descriptors[19],
        EndpointOperationId.GetDeviceEnrollmentStatus => Descriptors[20],
        EndpointOperationId.CancelDeviceEnrollment => Descriptors[21],
        EndpointOperationId.AddDeviceByCode => Descriptors[22],
        EndpointOperationId.RestoreRememberedSessions => Descriptors[23],
        EndpointOperationId.InitializeRememberMeSession => Descriptors[24],
        EndpointOperationId.SetRememberMe => Descriptors[25],
        EndpointOperationId.GetSavedPasswords => Descriptors[26],
        EndpointOperationId.AddNewPassword => Descriptors[27],
        EndpointOperationId.RemovePasswords => Descriptors[28],
        EndpointOperationId.GetUnsecurePassword => Descriptors[29],
        EndpointOperationId.UpdatePassword => Descriptors[30],
        EndpointOperationId.ExportPasswordsToUser => Descriptors[31],
        EndpointOperationId.AddCustomUserColors => Descriptors[32],
        EndpointOperationId.DeleteCustomUserColors => Descriptors[33],
        EndpointOperationId.ExportCustomUserColorsToUser => Descriptors[34],
        EndpointOperationId.UpdateCustomUserColor => Descriptors[35],
        EndpointOperationId.AddPasswordTag => Descriptors[36],
        EndpointOperationId.DeletePasswordTag => Descriptors[37],
        EndpointOperationId.ExportPasswordTagsToUser => Descriptors[38],
        EndpointOperationId.UpdatePasswordTag => Descriptors[39],
        _ => throw new ArgumentOutOfRangeException(nameof(operationId))
    };
}
