<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>PasswordManagerLocal.Windows.Agent</AssemblyName>
    <RootNamespace>PasswordManagerLocal.Windows.Agent</RootNamespace>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU;x64;x86;ARM64;ARM32</Platforms>
    <ApplicationIcon>Assets\app_icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Common\Backend\PasswordManagerLocal.Common.Backend.csproj" />
    <ProjectReference Include="..\..\Common\Backend.Hosting\PasswordManagerLocal.Common.Backend.Hosting.csproj" />
    <ProjectReference Include="..\Backend\PasswordManagerLocal.Windows.Backend.csproj" />
    <ProjectReference Include="..\..\Common\Contracts\PasswordManagerLocal.Common.Contracts.csproj" />
    <ProjectReference Include="..\..\Common\Preferences\PasswordManagerLocal.Common.Preferences.csproj" />
    <ProjectReference Include="..\EndpointRpc\PasswordManagerLocal.Windows.EndpointRpc.csproj" />
    <ProjectReference Include="..\IPC\PasswordManagerLocal.Windows.Ipc.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\app_icon.ico" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="PasswordManagerLocal.Windows.Tests.IPC" />
  </ItemGroup>
</Project>
